sudo: false
language: node_js
cache: npm

matrix:
  include:
    - os: linux
      node_js: "12"
    - os: osx
      osx_image: xcode11
      node_js: "12"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libx11-dev
      - zlib1g-dev
      - libpng-dev
      - libxtst-dev
      - g++-4.8
      - gcc-4.8

services:
  - xvfb

before_install:
  - node --version
  - npm --version

  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8 && $CXX --version; fi

install: true

script:
  - npm run patch && npm i
  - npm run build:release
  - cd test
  - npm cit
  - cd window-integration-tests
  - npm cit
  - cd ../..

stages:
  - test
  - name: deploy
    if: (branch = develop) OR (tag IS present)

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null

deploy:
  - provider: script
    skip_cleanup: false
    script: bash ./.build/pre-release.sh
    on:
      branch: develop
  - provider: script
    skip_cleanup: false
    script: bash ./.build/release.sh
    on:
      tags: true
