language: node_js
cache: npm

matrix:
  include:
    - os: linux
      dist: bionic
      node_js: "lts/dubnium"
    - os: osx
      osx_image: xcode11
      node_js: "lts/dubnium"
    - os: windows
      node_js: "lts/dubnium"

install: true

script:
  - npm run patch && npm i
  - if [[ $TRAVIS_OS_NAME = "windows" ]]; then npm run build:release:win; else npm run build:release; fi
  - npm test

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null

deploy:
  - provider: script
    skip_cleanup: true
    script: npm publish --access public
    on:
      tags: true
