name: Run CI

on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 2

jobs:
  test:
    name: Node ${{ matrix.node }}
    runs-on: windows-2019

    strategy:
      fail-fast: false
      matrix:
        node: [18]

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4.1.1
      - name: Set up node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{matrix.node}}
      - name: Install
        run: npm run patch && npm i
      - name: Build
        run: npm run build:release
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          working-directory: ./test/
          run: npm cit
      - name: Run window tests
        uses: GabrielBB/xvfb-action@v1
        with:
          working-directory: ./test/window-integration-tests
          run: npm cit
